baseURL = "https://getpapercss.com"
title = "PaperCSS"

# Directories
publishDir = "../public"

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
pygmentsStyle = "emacs"

[params.info]
description = "the less formal CSS framework"
title404 = "Nothing's here!"

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[blackfriday]
hrefTargetBlank = true
